"""Database creation

Revision ID: 8239a89905d7
Revises: 
Create Date: 2023-07-21 12:03:26.793661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8239a89905d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
